# site settings
title: AJ Blogs
subtitle: Blog page theme
email: youremailaddress@gmail.com
description: A simple and elegant jekyll theme for blogs.
baseurl: "/aj-jekyll-blog-theme"
url: "http://0.0.0.0:4000"
author:
street_address: 1234 Some street Road
city: Mumbai
state: Maharashtra
zip_code: 400001
country: India
phone: (+91) 9876543210

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com
googleplus_url: https://plus.google.com/
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/

# build settings
markdown: kramdown

sass:
  style: compressed
gems:
  - jekyll-paginate

plugins:
  [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"